# Generated by Django 4.2.16 on 2024-10-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('session_key', models.BigIntegerField(primary_key=True, serialize=False)),
                ('session_data', models.CharField(max_length=255)),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_2fa_enabled', models.BooleanField()),
                ('secret_key', models.CharField(max_length=255)),
                ('backup_codes', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('username_for_service', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='password_manager.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='password_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='MasterPasswordHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_hashed_password', models.CharField(max_length=255)),
                ('changed_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginAttempts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=255)),
                ('attempt_time', models.DateField()),
                ('was_successful', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.user'),
        ),
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=255)),
                ('action_description', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.user')),
            ],
        ),
    ]
