# Generated by Django 4.2.16 on 2024-11-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_twofactorcode_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoFactorCode',
        ),
    ]
