# Generated by Django 4.2.16 on 2024-11-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0005_delete_sessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
