# Generated by Django 4.2.16 on 2024-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0007_remove_user_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
