# Generated by Django 4.2.16 on 2024-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0009_remove_user_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryption_key',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
